version: '3.8'

services:
  backend:
    build: .
    container_name: backend
    env_file: .env
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - ./src/:/app/

  postgres:
    image: postgres:latest
    container_name: postgres
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  phppgadmin:
    image: dpage/pgadmin4
    container_name: phppgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - postgres
    ports:
      - "8081:80"

volumes:
  postgres_data:
